# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis2opengis
                                 A QGIS plugin
 Make Lite version of OpenGIS - open source webgis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-31
        copyright            : (C) 2023 by Andrea Ordonselli
        email                : info@opengis.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgis2opengis class from file qgis2openg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .qgis2opengis import qgis2opengis
    return qgis2opengis(iface)
